services:
  db-signature-project-management:
    hostname: db.signature.project_management.local
    container_name: db.signature.project_management.local
    build:
      context: .
      dockerfile: build/Dockerfile.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 10
    restart: always
    environment:
      - TZ=America/Santiago
      - PGTZ=America/Santiago
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '31000:5432'
    volumes: 
      - db-signature-project-management:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project-management-network

  backend-signature-project-management:
    hostname: backend.signature.project_management.local
    container_name: backend.signature.project_management.local
    build:
      context: .
      dockerfile: build/Dockerfile
    depends_on:
      db-signature-project-management:  
        condition: service_healthy
    environment:
      DB_HOST: db.signature.project_management.local  
      DB_PORT: 5432
      DB_NAME: signature_project
      JWT_SECRET: 'secreto'
      APP_ENV: staging
    ports:
      - "32000:3000"
    networks:
      - project-management-network
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonardb
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - project-management-network

  sonardb:
    image: postgres:15
    container_name: sonardb
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data
    networks:
      - project-management-network

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_db:
  db-signature-project-management:  
    driver: local
networks:
  project-management-network:
    external: true